window.PORTFOLIO_DATA = {
  "meta": {
    "priceDate": "2026-06-01",
    "targetCapital": 256024.18,
    "currentPortfolioValue": 256024.18,
    "modelPortfolioValue": 254724.57,
    "residualValue": 1299.61,
    "cashCurrent": 26854.02,
    "liquidityCurrentValue": 34940.22,
    "cashTargetPct": 8.0,
    "cashMinimumPct": 5.0,
    "liquidityTargetPct": 15.0,
    "liquidityCurrentPct": 13.65,
    "residualCount": 4,
    "modelAssetCount": 26,
    "holdingsCount": 21,
    "watchlistCount": 34,
    "marketPriceCount": 53,
    "fxRateCount": 3,
    "notes": [
      "O modelo usa o fechamento mais recente do snapshot em 2026-06-01 e converte tudo para USD.",
      "Cash, XOVR e bond ECOPET formam a faixa de liquidez/defesa.",
      "Posicoes residuais fora do modelo aparecem separadas para nao mascarar risco."
    ],
    "baseTopFiveShare": 31.0,
    "nonUsdShare": 2.0
  },
  "scenarios": [
    {
      "id": "study",
      "label": "Base do estudo",
      "description": "Replica o plano principal e preserva o corredor de liquidez de 15%.",
      "cashTargetPct": 8.0,
      "xovrTargetPct": 4.0,
      "bondTargetPct": 3.0,
      "themeMultipliers": {
        "quality": 1.0,
        "defense_space": 1.0,
        "uranium": 1.0,
        "minerals": 1.0,
        "tail": 1.0
      }
    },
    {
      "id": "defensive",
      "label": "Defensivo global",
      "description": "Sobe caixa, corta a cauda e privilegia o nucleo de qualidade.",
      "cashTargetPct": 10.0,
      "xovrTargetPct": 4.0,
      "bondTargetPct": 3.0,
      "themeMultipliers": {
        "quality": 1.06,
        "defense_space": 0.95,
        "uranium": 0.9,
        "minerals": 0.85,
        "tail": 0.6
      }
    },
    {
      "id": "convex",
      "label": "Convexidade",
      "description": "Reduz caixa e amplifica optionalidade em energia, defesa e minerais.",
      "cashTargetPct": 6.0,
      "xovrTargetPct": 4.0,
      "bondTargetPct": 3.0,
      "themeMultipliers": {
        "quality": 0.94,
        "defense_space": 1.05,
        "uranium": 1.16,
        "minerals": 1.12,
        "tail": 1.35
      }
    }
  ],
  "themes": [
    {
      "id": "liquidity",
      "label": "Liquidez",
      "description": "Cash, XOVR e o bond ECOPET preservam a faixa de defesa do modelo.",
      "accent": "#d08b2e",
      "assets": [
        "Cash",
        "XOVR",
        "ECOPET_BOND"
      ],
      "assetCount": 3
    },
    {
      "id": "quality",
      "label": "Nucleo qualidade",
      "description": "MSFT, NVDA, AMZN, GOOGL, JPM e IBM financiam a carteira e reduzem ruído.",
      "accent": "#4aa3df",
      "assets": [
        "AMZN",
        "GOOGL",
        "MSFT",
        "NVDA",
        "IBM",
        "JPM"
      ],
      "assetCount": 6
    },
    {
      "id": "defense_space",
      "label": "Defesa e espaco",
      "description": "RKLB, ASTS, KTOS, SHLD e RTX capturam a tese geopolitica e orbital.",
      "accent": "#7e8cff",
      "assets": [
        "RTX",
        "KTOS",
        "SHLD",
        "RKLB",
        "ASTS"
      ],
      "assetCount": 5
    },
    {
      "id": "uranium",
      "label": "Uranio e nuclear",
      "description": "URA, NXE, SMR, UUUU e NAUFF refletem o ciclo de energia estrategica.",
      "accent": "#c86df0",
      "assets": [
        "URA",
        "NXE",
        "SMR",
        "UUUU",
        "NAUFF"
      ],
      "assetCount": 5
    },
    {
      "id": "minerals",
      "label": "Minerais criticos",
      "description": "COPX, ARR, MP e SGML conectam cobre, terras raras e lito ao superciclo.",
      "accent": "#2bc6a4",
      "assets": [
        "COPX",
        "ARR.AX",
        "MP",
        "SGML"
      ],
      "assetCount": 4
    },
    {
      "id": "tail",
      "label": "Cauda especulativa",
      "description": "QBTS, RGTI, LAES, HYMC e USGDF ficam como opcionalidade de cauda.",
      "accent": "#ff7a59",
      "assets": [
        "QBTS",
        "RGTI",
        "LAES",
        "HYMC",
        "USGDF"
      ],
      "assetCount": 5
    }
  ],
  "study": {
    "principles": [
      "Construa um basket, nao uma aposta unica.",
      "Aceite que varias teses falhem; poucos vencedores pagam a conta.",
      "Use ativos estrategicos com potencial de rerating estrutural.",
      "Preserve liquidez e respeite o piso de 5% em caixa.",
      "Dimensone optionalidade por tema, geografia e horizonte."
    ],
    "basketBlueprint": [
      {
        "label": "Rare earths",
        "weight": 20,
        "examples": [
          "ARR",
          "Ucore",
          "Aclara",
          "Energy Fuels"
        ]
      },
      {
        "label": "Uranium",
        "weight": 20,
        "examples": [
          "NXE",
          "DNN",
          "FCU",
          "DYL"
        ]
      },
      {
        "label": "Defense / space",
        "weight": 20,
        "examples": [
          "ASTS",
          "RKLB",
          "KTOS",
          "RCAT"
        ]
      },
      {
        "label": "AI biotech",
        "weight": 15,
        "examples": [
          "RXRX",
          "BEAM",
          "CRSP"
        ]
      },
      {
        "label": "Copper / lithium",
        "weight": 15,
        "examples": [
          "IVN",
          "SGML",
          "PMET",
          "LAAC"
        ]
      },
      {
        "label": "Nuclear",
        "weight": 10,
        "examples": [
          "SMR",
          "OKLO"
        ]
      }
    ],
    "topIdeas": [
      {
        "symbol": "ARR",
        "name": "American Rare Earths",
        "themeLabel": "Minerais criticos",
        "studyBucket": "rare_earths",
        "priority": "alta",
        "currency": "AUD",
        "currentPrice": 0.39,
        "currentPriceUsd": 0.28,
        "targetPrice": 0.57,
        "targetPriceUsd": 0.41,
        "upsidePct": 45.0,
        "thesis": "top 5; terras raras EUA, geopolítica, muito risco"
      },
      {
        "symbol": "ASTS",
        "name": "AST SpaceMobile",
        "themeLabel": "Defesa e espaco",
        "studyBucket": "defense_space",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 105.65,
        "currentPriceUsd": 105.65,
        "targetPrice": 147.91,
        "targetPriceUsd": 147.91,
        "upsidePct": 40.0,
        "thesis": "top 5; infraestrutura celular via satélite"
      },
      {
        "symbol": "NXE",
        "name": "NexGen Energy",
        "themeLabel": "Uranio e nuclear",
        "studyBucket": "uranium",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 11.4,
        "currentPriceUsd": 11.4,
        "targetPrice": 14.82,
        "targetPriceUsd": 14.82,
        "upsidePct": 30.0,
        "thesis": "top 5; ativo tier-1 em urânio"
      },
      {
        "symbol": "RKLB",
        "name": "Rocket Lab",
        "themeLabel": "Cauda especulativa",
        "studyBucket": "Espaço/defesa",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 122.39,
        "currentPriceUsd": 122.39,
        "targetPrice": 165.23,
        "targetPriceUsd": 165.23,
        "upsidePct": 35.0,
        "thesis": "top 5; execução operacional"
      },
      {
        "symbol": "SMR",
        "name": "NuScale Power",
        "themeLabel": "Cauda especulativa",
        "studyBucket": "Nuclear SMR",
        "priority": "alta",
        "currency": "USD",
        "currentPrice": 12.89,
        "currentPriceUsd": 12.89,
        "targetPrice": 16.76,
        "targetPriceUsd": 16.76,
        "upsidePct": 30.0,
        "thesis": "top 5; opcionalidade em SMRs"
      }
    ]
  },
  "marketPrices": [
    {
      "symbol": "ALL.L",
      "yahoo": "ALL.L",
      "currency": "GBP",
      "currencyRaw": "GBp",
      "closeLocal": 0.17,
      "closeUsd": 0.22,
      "fxToUsd": 1.346,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ALL.L?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "AMZN",
      "yahoo": "AMZN",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 261.26,
      "closeUsd": 261.26,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/AMZN?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "ARA.TO",
      "yahoo": "ARA.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 4.45,
      "closeUsd": 3.22,
      "fxToUsd": 0.722585,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ARA.TO?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "ARR.AX",
      "yahoo": "ARR.AX",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "closeLocal": 0.39,
      "closeUsd": 0.28,
      "fxToUsd": 0.71643,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ARR.AX?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "ASCU.TO",
      "yahoo": "ASCU.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 10.26,
      "closeUsd": 7.41,
      "fxToUsd": 0.722585,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ASCU.TO?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "ASTS",
      "yahoo": "ASTS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 105.65,
      "closeUsd": 105.65,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ASTS?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "BEAM",
      "yahoo": "BEAM",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 31.14,
      "closeUsd": 31.14,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/BEAM?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "BKSY",
      "yahoo": "BKSY",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 42.38,
      "closeUsd": 42.38,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/BKSY?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "CDZI",
      "yahoo": "CDZI",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 4.7,
      "closeUsd": 4.7,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/CDZI?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "COPX",
      "yahoo": "COPX",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 90.06,
      "closeUsd": 90.06,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/COPX?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "CRSP",
      "yahoo": "CRSP",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 54.19,
      "closeUsd": 54.19,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/CRSP?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "DNN",
      "yahoo": "DNN",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 3.43,
      "closeUsd": 3.43,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/DNN?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "DYL.AX",
      "yahoo": "DYL.AX",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "closeLocal": 1.6,
      "closeUsd": 1.14,
      "fxToUsd": 0.71643,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/DYL.AX?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "FCU.TO",
      "yahoo": "FCU.TO",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "source": "yahoo",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/FCU.TO?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "GLO.TO",
      "yahoo": "GLO.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 0.74,
      "closeUsd": 0.53,
      "fxToUsd": 0.722585,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/GLO.TO?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "GOOGL",
      "yahoo": "GOOGL",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 376.37,
      "closeUsd": 376.37,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/GOOGL?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "HYMC",
      "yahoo": "HYMC",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 32.84,
      "closeUsd": 32.84,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/HYMC?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "IBM",
      "yahoo": "IBM",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 320.42,
      "closeUsd": 320.42,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/IBM?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "ICG.CN",
      "yahoo": "ICG.CN",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 0.46,
      "closeUsd": 0.33,
      "fxToUsd": 0.722585,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/ICG.CN?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "IVN.TO",
      "yahoo": "IVN.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 12.76,
      "closeUsd": 9.22,
      "fxToUsd": 0.722585,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/IVN.TO?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "JPM",
      "yahoo": "JPM",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 296.58,
      "closeUsd": 296.58,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/JPM?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "KTOS",
      "yahoo": "KTOS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 63.49,
      "closeUsd": 63.49,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/KTOS?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "LAAC",
      "yahoo": "LAAC",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "source": "yahoo",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/LAAC?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "LAES",
      "yahoo": "LAES",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 3.55,
      "closeUsd": 3.55,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/LAES?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "LYC.AX",
      "yahoo": "LYC.AX",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "closeLocal": 18.67,
      "closeUsd": 13.38,
      "fxToUsd": 0.71643,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/LYC.AX?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "MOS",
      "yahoo": "MOS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 23.33,
      "closeUsd": 23.33,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/MOS?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "MP",
      "yahoo": "MP",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 69.29,
      "closeUsd": 69.29,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/MP?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "MSFT",
      "yahoo": "MSFT",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 460.52,
      "closeUsd": 460.52,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/MSFT?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "NAUFF",
      "yahoo": "NAUFF",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 2.08,
      "closeUsd": 2.08,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NAUFF?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "NGEX.V",
      "yahoo": "NGEX.V",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "source": "yahoo",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NGEX.V?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "NTDOY",
      "yahoo": "NTDOY",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 11.25,
      "closeUsd": 11.25,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NTDOY?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "NTR",
      "yahoo": "NTR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 69.57,
      "closeUsd": 69.57,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NTR?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "NVDA",
      "yahoo": "NVDA",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 224.36,
      "closeUsd": 224.36,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NVDA?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "NXE",
      "yahoo": "NXE",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 11.4,
      "closeUsd": 11.4,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/NXE?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "OKLO",
      "yahoo": "OKLO",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 66.89,
      "closeUsd": 66.89,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/OKLO?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "PL",
      "yahoo": "PL",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 46.46,
      "closeUsd": 46.46,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/PL?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "PLTR",
      "yahoo": "PLTR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 160.65,
      "closeUsd": 160.65,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/PLTR?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "PMET.V",
      "yahoo": "PMET.V",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": null,
      "closeUsd": null,
      "fxToUsd": 1.0,
      "date": "",
      "error": "HTTP Error 404: Not Found",
      "source": "yahoo",
      "status": "missing",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/PMET.V?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "QBTS",
      "yahoo": "QBTS",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 29.18,
      "closeUsd": 29.18,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/QBTS?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "RCAT",
      "yahoo": "RCAT",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 14.84,
      "closeUsd": 14.84,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RCAT?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "RGTI",
      "yahoo": "RGTI",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 25.63,
      "closeUsd": 25.63,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RGTI?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "RKLB",
      "yahoo": "RKLB",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 122.39,
      "closeUsd": 122.39,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RKLB?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "RTX",
      "yahoo": "RTX",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 174.41,
      "closeUsd": 174.41,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RTX?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "RXRX",
      "yahoo": "RXRX",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 3.79,
      "closeUsd": 3.79,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/RXRX?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "SGML",
      "yahoo": "SGML",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 16.36,
      "closeUsd": 16.36,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SGML?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "SHLD",
      "yahoo": "SHLD",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 65.62,
      "closeUsd": 65.62,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SHLD?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "SLS.TO",
      "yahoo": "SLS.TO",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "closeLocal": 14.75,
      "closeUsd": 10.66,
      "fxToUsd": 0.722585,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SLS.TO?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "SMR",
      "yahoo": "SMR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 12.89,
      "closeUsd": 12.89,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/SMR?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "URA",
      "yahoo": "URA",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 50.54,
      "closeUsd": 50.54,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/URA?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "USGDF",
      "yahoo": "USGDF",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 0.12,
      "closeUsd": 0.12,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/USGDF?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "UURAF",
      "yahoo": "UURAF",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 4.09,
      "closeUsd": 4.09,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/UURAF?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "UUUU",
      "yahoo": "UUUU",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 17.62,
      "closeUsd": 17.62,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/UUUU?period1=1779062400&period2=1780531200&interval=1d&events=history"
    },
    {
      "symbol": "XOVR",
      "yahoo": "XOVR",
      "currency": "USD",
      "currencyRaw": "USD",
      "closeLocal": 20.58,
      "closeUsd": 20.58,
      "fxToUsd": 1.0,
      "date": "2026-06-01",
      "error": "",
      "source": "yahoo",
      "status": "ok",
      "url": "https://query1.finance.yahoo.com/v8/finance/chart/XOVR?period1=1779062400&period2=1780531200&interval=1d&events=history"
    }
  ],
  "fxRates": [
    {
      "currency": "AUD",
      "rate": 0.7164298892021179,
      "pair": "AUDUSD=X",
      "date": "2026-06-01",
      "error": "",
      "multiplier": 1.0
    },
    {
      "currency": "CAD",
      "rate": 0.722585141658783,
      "pair": "CADUSD=X",
      "date": "2026-06-01",
      "error": "",
      "multiplier": 1.0
    },
    {
      "currency": "GBP",
      "rate": 1.3460001945495605,
      "pair": "GBPUSD=X",
      "date": "2026-06-01",
      "error": "",
      "multiplier": 0.01
    },
    {
      "currency": "USD",
      "rate": 1.0,
      "pair": "USD",
      "date": "2026-06-01",
      "error": "",
      "multiplier": 1.0
    }
  ],
  "moves": [
    {
      "asset": "Cash",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "category": "Liquidez",
      "role": "Reserva",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 8.0,
      "baseTargetValue": 20481.93,
      "currentValue": 26854.02,
      "currentValueLocal": 0.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "baseTradeValue": -6372.09,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Preservar liquidez estrategica e cumprir o piso de 5% com folga.",
      "fixed": true,
      "priceDate": "",
      "priceError": ""
    },
    {
      "asset": "XOVR",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "category": "Liquidez",
      "role": "Reserva",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 10240.97,
      "currentValue": 2058.0,
      "currentValueLocal": 2058.0,
      "currentPrice": 20.58,
      "currentPriceUsd": 20.58,
      "baseTradeValue": 8182.97,
      "targetPrice": 21.4,
      "targetPriceUsd": 21.4,
      "upsidePct": 4.0,
      "bias": "manter como caixa equivalente",
      "thesis": "Aumentar equivalente defensivo para reduzir volatilidade sem sair de caixa.",
      "fixed": true,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "ECOPET_BOND",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "category": "Liquidez",
      "role": "Reserva",
      "region": "Colombia",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 3.0,
      "baseTargetValue": 7680.73,
      "currentValue": 6028.2,
      "currentValueLocal": 0.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "baseTradeValue": 1652.53,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Manter renda fixa em USD como camada defensiva do modelo.",
      "fixed": true,
      "priceDate": "",
      "priceError": ""
    },
    {
      "asset": "AMZN",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "AMZN",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 5.0,
      "baseTargetValue": 12801.21,
      "currentValue": 13063.0,
      "currentValueLocal": 13063.0,
      "currentPrice": 261.26,
      "currentPriceUsd": 261.26,
      "baseTradeValue": -261.79,
      "targetPrice": 297.84,
      "targetPriceUsd": 297.84,
      "upsidePct": 14.0,
      "bias": "manter/aumentar moderado",
      "thesis": "Manter qualidade em cloud, ads e consumo, apenas aparando excesso pequeno.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "GOOGL",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "GOOGL",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 5.0,
      "baseTargetValue": 12801.21,
      "currentValue": 9409.25,
      "currentValueLocal": 9409.25,
      "currentPrice": 376.37,
      "currentPriceUsd": 376.37,
      "baseTradeValue": 3391.96,
      "targetPrice": 421.53,
      "targetPriceUsd": 421.53,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "Aumentar para peso de nucleo pela combinacao de IA, search e cloud.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "MSFT",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "MSFT",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 6.0,
      "baseTargetValue": 15361.45,
      "currentValue": 23026.0,
      "currentValueLocal": 23026.0,
      "currentPrice": 460.52,
      "currentPriceUsd": 460.52,
      "baseTradeValue": -7664.55,
      "targetPrice": 506.57,
      "targetPriceUsd": 506.57,
      "upsidePct": 10.0,
      "bias": "manter",
      "thesis": "Preservar posicao core em cloud/IA, mas reduzir concentracao para financiar convexidade.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "NVDA",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "NVDA",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 8.0,
      "baseTargetValue": 20481.93,
      "currentValue": 44872.0,
      "currentValueLocal": 44872.0,
      "currentPrice": 224.36,
      "currentPriceUsd": 224.36,
      "baseTradeValue": -24390.07,
      "targetPrice": 246.8,
      "targetPriceUsd": 246.8,
      "upsidePct": 10.0,
      "bias": "reduzir peso",
      "thesis": "Continuar exposto a lideranca em IA, porem com disciplina de tamanho.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "IBM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "IBM",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 10240.97,
      "currentValue": 32042.0,
      "currentValueLocal": 32042.0,
      "currentPrice": 320.42,
      "currentPriceUsd": 320.42,
      "baseTradeValue": -21801.03,
      "targetPrice": 333.24,
      "targetPriceUsd": 333.24,
      "upsidePct": 4.0,
      "bias": "reduzir",
      "thesis": "Reduzir ativo defensivo de menor convexidade para liberar capital para teses do estudo.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "JPM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "category": "JPM",
      "role": "Ancoragem",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 6.0,
      "baseTargetValue": 15361.45,
      "currentValue": 29658.0,
      "currentValueLocal": 29658.0,
      "currentPrice": 296.58,
      "currentPriceUsd": 296.58,
      "baseTradeValue": -14296.55,
      "targetPrice": 314.37,
      "targetPriceUsd": 314.37,
      "upsidePct": 6.0,
      "bias": "reduzir",
      "thesis": "Manter banco de qualidade, mas reduzir peso elevado e dependencia de financeiro tradicional.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "RTX",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "RTX",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 3.0,
      "baseTargetValue": 7680.73,
      "currentValue": 5232.3,
      "currentValueLocal": 5232.3,
      "currentPrice": 174.41,
      "currentPriceUsd": 174.41,
      "baseTradeValue": 2448.43,
      "targetPrice": 188.36,
      "targetPriceUsd": 188.36,
      "upsidePct": 8.0,
      "bias": "manter",
      "thesis": "Reforcar defesa core, com menor upside que RKLB e KTOS, mas melhor perfil defensivo.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "KTOS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "KTOS",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 10240.97,
      "currentValue": 3809.4,
      "currentValueLocal": 3809.4,
      "currentPrice": 63.49,
      "currentPriceUsd": 63.49,
      "baseTradeValue": 6431.57,
      "targetPrice": 74.92,
      "targetPriceUsd": 74.92,
      "upsidePct": 18.0,
      "bias": "manter",
      "thesis": "Aumentar exposicao a drones, sistemas autonomos e guerra eletronica.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "SHLD",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "SHLD",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 10240.97,
      "currentValue": 9843.0,
      "currentValueLocal": 9843.0,
      "currentPrice": 65.62,
      "currentPriceUsd": 65.62,
      "baseTradeValue": 397.97,
      "targetPrice": 73.49,
      "targetPriceUsd": 73.49,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "Manter ETF de defesa como exposicao diversificada ao tema geopolitico.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "URA",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "URA",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 5.0,
      "baseTargetValue": 12801.21,
      "currentValue": 5054.0,
      "currentValueLocal": 5054.0,
      "currentPrice": 50.54,
      "currentPriceUsd": 50.54,
      "baseTradeValue": 7747.21,
      "targetPrice": 58.12,
      "targetPriceUsd": 58.12,
      "upsidePct": 15.0,
      "bias": "manter",
      "thesis": "Aumentar bloco de uranio pelo ciclo nuclear e pela demanda de energia para IA.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "COPX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "COPX",
      "role": "Opcionalidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 10240.97,
      "currentValue": 9006.0,
      "currentValueLocal": 9006.0,
      "currentPrice": 90.06,
      "currentPriceUsd": 90.06,
      "baseTradeValue": 1234.97,
      "targetPrice": 100.87,
      "targetPriceUsd": 100.87,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "Reforcar cobre como tese de eletrificacao global com risco mais diversificado.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "RKLB",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "RKLB",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 6.0,
      "baseTargetValue": 15361.45,
      "currentValue": 7343.4,
      "currentValueLocal": 7343.4,
      "currentPrice": 122.39,
      "currentPriceUsd": 122.39,
      "baseTradeValue": 8018.05,
      "targetPrice": 165.23,
      "targetPriceUsd": 165.23,
      "upsidePct": 35.0,
      "bias": "aumentar",
      "thesis": "Aumentar uma das top 5 do estudo, com execucao operacional real em espaco e defesa.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "ASTS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "category": "ASTS",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 10240.97,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 105.65,
      "currentPriceUsd": 105.65,
      "baseTradeValue": 10240.97,
      "targetPrice": 105.65,
      "targetPriceUsd": 105.65,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Iniciar exposicao a infraestrutura celular via satelite, uma das maiores optionalidades.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "NXE",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "NXE",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 4.0,
      "baseTargetValue": 10240.97,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 11.4,
      "currentPriceUsd": 11.4,
      "baseTradeValue": 10240.97,
      "targetPrice": 11.4,
      "targetPriceUsd": 11.4,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Iniciar posicao em ativo tier-1 de uranio, destacado como qualidade geologica superior.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "SMR",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "SMR",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 3.0,
      "baseTargetValue": 7680.73,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 12.89,
      "currentPriceUsd": 12.89,
      "baseTradeValue": 7680.73,
      "targetPrice": 12.89,
      "targetPriceUsd": 12.89,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Iniciar exposicao a SMRs, tese nuclear com opcionalidade estrategica.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "ARR.AX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "ARR.AX",
      "role": "Opcionalidade",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.71643,
      "baseWeightPct": 2.0,
      "baseTargetValue": 5120.48,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 0.39,
      "currentPriceUsd": 0.27940770000000004,
      "baseTradeValue": 5120.48,
      "targetPrice": 0.39,
      "targetPriceUsd": 0.27940770000000004,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar rare earths geopolitico dos EUA em tamanho controlado pelo risco elevado.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "MP",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "MP",
      "role": "Opcionalidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 5120.48,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 69.29,
      "currentPriceUsd": 69.29,
      "baseTradeValue": 5120.48,
      "targetPrice": 69.29,
      "targetPriceUsd": 69.29,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar rare earths em producao nos EUA, com menor risco relativo que ARR.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "UUUU",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "UUUU",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 5120.48,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 17.62,
      "currentPriceUsd": 17.62,
      "baseTradeValue": 5120.48,
      "targetPrice": 17.62,
      "targetPriceUsd": 17.62,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar hibrido de uranio, monazita e rare earths para ampliar a cesta estrategica.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "SGML",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "category": "SGML",
      "role": "Opcionalidade",
      "region": "Brazil",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 5120.48,
      "currentValue": 0.0,
      "currentValueLocal": 0.0,
      "currentPrice": 16.36,
      "currentPriceUsd": 16.36,
      "baseTradeValue": 5120.48,
      "targetPrice": 16.36,
      "targetPriceUsd": 16.36,
      "upsidePct": 0.0,
      "bias": "",
      "thesis": "Adicionar litio Brasil/ESG como opcionalidade de supply chain critica.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "QBTS",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "category": "QBTS",
      "role": "Cauda",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 2.0,
      "baseTargetValue": 5120.48,
      "currentValue": 14590.0,
      "currentValueLocal": 14590.0,
      "currentPrice": 29.18,
      "currentPriceUsd": 29.18,
      "baseTradeValue": -9469.52,
      "targetPrice": 35.02,
      "targetPriceUsd": 35.02,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "Reduzir quantum para tamanho de cesta, diminuindo risco de diluicao e volatilidade extrema.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "RGTI",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "category": "RGTI",
      "role": "Cauda",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 1.5,
      "baseTargetValue": 3840.36,
      "currentValue": 5126.0,
      "currentValueLocal": 5126.0,
      "currentPrice": 25.63,
      "currentPriceUsd": 25.63,
      "baseTradeValue": -1285.64,
      "targetPrice": 30.76,
      "targetPriceUsd": 30.76,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "Manter opcionalidade em quantum, mas com peso menor e compativel com risco binario.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "LAES",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "category": "LAES",
      "role": "Cauda",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 1.5,
      "baseTargetValue": 3840.36,
      "currentValue": 3550.0,
      "currentValueLocal": 3550.0,
      "currentPrice": 3.55,
      "currentPriceUsd": 3.55,
      "baseTradeValue": 290.36,
      "targetPrice": 4.44,
      "targetPriceUsd": 4.44,
      "upsidePct": 25.0,
      "bias": "reduzir para cesta",
      "thesis": "Manter microcap de seguranca/semis apenas como componente pequeno da cesta.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "asset": "NAUFF",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "category": "NAUFF",
      "role": "Estrutural",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "baseWeightPct": 1.0,
      "baseTargetValue": 2560.24,
      "currentValue": 4160.0,
      "currentValueLocal": 4160.0,
      "currentPrice": 2.08,
      "currentPriceUsd": 2.08,
      "baseTradeValue": -1599.76,
      "targetPrice": 2.6,
      "targetPriceUsd": 2.6,
      "upsidePct": 25.0,
      "bias": "manter pequeno",
      "thesis": "Reduzir para posicao pequena, mantendo opcionalidade no ciclo nuclear sem concentrar risco.",
      "fixed": false,
      "priceDate": "2026-06-01",
      "priceError": ""
    }
  ],
  "holdings": [
    {
      "symbol": "ICG",
      "name": "ICG",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.722585,
      "currentPrice": 0.46,
      "currentPriceUsd": 0.33,
      "targetPrice": 0.46,
      "targetPriceUsd": 0.33,
      "upsidePct": 0.0,
      "bias": "manter apenas residual",
      "thesis": "posição residual CAD; baixa liquidez",
      "currentValueLocal": 3.68,
      "currentValue": 2.66,
      "modelTargetWeightPct": 0.0,
      "targetValue": 2.64,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "AMZN",
      "name": "AMZN",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 261.26,
      "currentPriceUsd": 261.26,
      "targetPrice": 297.84,
      "targetPriceUsd": 297.84,
      "upsidePct": 14.0,
      "bias": "manter/aumentar moderado",
      "thesis": "cloud, ads e consumo; qualidade alta",
      "currentValueLocal": 13063.0,
      "currentValue": 13063.0,
      "modelTargetWeightPct": 5.0,
      "targetValue": 14891.999999999998,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "AMZN",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "COPX",
      "name": "COPX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 90.06,
      "currentPriceUsd": 90.06,
      "targetPrice": 100.87,
      "targetPriceUsd": 100.87,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "eletrificação e déficit estrutural de cobre",
      "currentValueLocal": 9006.0,
      "currentValue": 9006.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 10087.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "COPX",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "GOOGL",
      "name": "GOOGL",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 376.37,
      "currentPriceUsd": 376.37,
      "targetPrice": 421.53,
      "targetPriceUsd": 421.53,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "IA/search/cloud; valuation ainda razoável",
      "currentValueLocal": 9409.25,
      "currentValue": 9409.25,
      "modelTargetWeightPct": 5.0,
      "targetValue": 10538.25,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "GOOGL",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "HYMC",
      "name": "HYMC",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 32.84,
      "currentPriceUsd": 32.84,
      "targetPrice": 29.56,
      "targetPriceUsd": 29.56,
      "upsidePct": -10.0,
      "bias": "zerar ou residual",
      "thesis": "opcionalidade alta, execução fraca",
      "currentValueLocal": 328.4,
      "currentValue": 328.4,
      "modelTargetWeightPct": 0.0,
      "targetValue": 295.59999999999997,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "IBM",
      "name": "IBM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 320.42,
      "currentPriceUsd": 320.42,
      "targetPrice": 333.24,
      "targetPriceUsd": 333.24,
      "upsidePct": 4.0,
      "bias": "reduzir",
      "thesis": "defensiva, IA corporativa, menor convexidade",
      "currentValueLocal": 32042.0,
      "currentValue": 32042.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 33324.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "IBM",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "JPM",
      "name": "JPM",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 296.58,
      "currentPriceUsd": 296.58,
      "targetPrice": 314.37,
      "targetPriceUsd": 314.37,
      "upsidePct": 6.0,
      "bias": "reduzir",
      "thesis": "banco de qualidade, mas peso atual alto",
      "currentValueLocal": 29658.0,
      "currentValue": 29658.0,
      "modelTargetWeightPct": 6.0,
      "targetValue": 31437.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "JPM",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "KTOS",
      "name": "KTOS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 63.49,
      "currentPriceUsd": 63.49,
      "targetPrice": 74.92,
      "targetPriceUsd": 74.92,
      "upsidePct": 18.0,
      "bias": "manter",
      "thesis": "drones, sistemas autônomos e defesa",
      "currentValueLocal": 3809.4,
      "currentValue": 3809.4,
      "modelTargetWeightPct": 4.0,
      "targetValue": 4495.2,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "KTOS",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "LAES",
      "name": "LAES",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 3.55,
      "currentPriceUsd": 3.55,
      "targetPrice": 4.44,
      "targetPriceUsd": 4.44,
      "upsidePct": 25.0,
      "bias": "reduzir para cesta",
      "thesis": "microcap com opcionalidade e risco",
      "currentValueLocal": 3550.0,
      "currentValue": 3550.0,
      "modelTargetWeightPct": 1.5,
      "targetValue": 4440.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "LAES",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "MSFT",
      "name": "MSFT",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 460.52,
      "currentPriceUsd": 460.52,
      "targetPrice": 506.57,
      "targetPriceUsd": 506.57,
      "upsidePct": 10.0,
      "bias": "manter",
      "thesis": "cloud/IA; qualidade máxima",
      "currentValueLocal": 23026.0,
      "currentValue": 23026.0,
      "modelTargetWeightPct": 6.0,
      "targetValue": 25328.5,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "MSFT",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "NAUFF",
      "name": "NAUFF",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 2.08,
      "currentPriceUsd": 2.08,
      "targetPrice": 2.6,
      "targetPriceUsd": 2.6,
      "upsidePct": 25.0,
      "bias": "manter pequeno",
      "thesis": "opcionalidade em ciclo nuclear",
      "currentValueLocal": 4160.0,
      "currentValue": 4160.0,
      "modelTargetWeightPct": 1.0,
      "targetValue": 5200.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "NAUFF",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "NTDOY",
      "name": "NTDOY",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 11.25,
      "currentPriceUsd": 11.25,
      "targetPrice": 12.04,
      "targetPriceUsd": 12.04,
      "upsidePct": 7.0,
      "bias": "reduzir",
      "thesis": "qualidade, mas fora das teses anexas",
      "currentValueLocal": 843.75,
      "currentValue": 843.75,
      "modelTargetWeightPct": 0.0,
      "targetValue": 902.9999999999999,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "NVDA",
      "name": "NVDA",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 224.36,
      "currentPriceUsd": 224.36,
      "targetPrice": 246.8,
      "targetPriceUsd": 246.8,
      "upsidePct": 10.0,
      "bias": "reduzir peso",
      "thesis": "liderança em IA, valuation exige disciplina",
      "currentValueLocal": 44872.0,
      "currentValue": 44872.0,
      "modelTargetWeightPct": 8.0,
      "targetValue": 49360.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "NVDA",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "QBTS",
      "name": "QBTS",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 29.18,
      "currentPriceUsd": 29.18,
      "targetPrice": 35.02,
      "targetPriceUsd": 35.02,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "alto beta e risco de diluição",
      "currentValueLocal": 14590.0,
      "currentValue": 14590.0,
      "modelTargetWeightPct": 2.0,
      "targetValue": 17510.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "QBTS",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "RGTI",
      "name": "RGTI",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 25.63,
      "currentPriceUsd": 25.63,
      "targetPrice": 30.76,
      "targetPriceUsd": 30.76,
      "upsidePct": 20.0,
      "bias": "reduzir",
      "thesis": "alto beta e risco de diluição",
      "currentValueLocal": 5126.0,
      "currentValue": 5126.0,
      "modelTargetWeightPct": 1.5,
      "targetValue": 6152.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "RGTI",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "RKLB",
      "name": "RKLB",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 122.39,
      "currentPriceUsd": 122.39,
      "targetPrice": 165.23,
      "targetPriceUsd": 165.23,
      "upsidePct": 35.0,
      "bias": "aumentar",
      "thesis": "uma das top 5 dos anexos; execução real",
      "currentValueLocal": 7343.4,
      "currentValue": 7343.4,
      "modelTargetWeightPct": 6.0,
      "targetValue": 9913.8,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "RKLB",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "RTX",
      "name": "RTX",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 174.41,
      "currentPriceUsd": 174.41,
      "targetPrice": 188.36,
      "targetPriceUsd": 188.36,
      "upsidePct": 8.0,
      "bias": "manter",
      "thesis": "defesa defensiva, menor upside que KTOS/RKLB",
      "currentValueLocal": 5232.3,
      "currentValue": 5232.3,
      "modelTargetWeightPct": 3.0,
      "targetValue": 5650.8,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "RTX",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "SHLD",
      "name": "SHLD",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 65.62,
      "currentPriceUsd": 65.62,
      "targetPrice": 73.49,
      "targetPriceUsd": 73.49,
      "upsidePct": 12.0,
      "bias": "manter",
      "thesis": "defesa/segurança como tema estrutural",
      "currentValueLocal": 9843.0,
      "currentValue": 9843.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 11023.5,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "SHLD",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "URA",
      "name": "URA",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 50.54,
      "currentPriceUsd": 50.54,
      "targetPrice": 58.12,
      "targetPriceUsd": 58.12,
      "upsidePct": 15.0,
      "bias": "manter",
      "thesis": "ciclo nuclear e demanda de energia para IA",
      "currentValueLocal": 5054.0,
      "currentValue": 5054.0,
      "modelTargetWeightPct": 5.0,
      "targetValue": 5812.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "URA",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "USGDF",
      "name": "USGDF",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.12,
      "currentPriceUsd": 0.12,
      "targetPrice": 0.12,
      "targetPriceUsd": 0.12,
      "upsidePct": 0.0,
      "bias": "zerar se possível",
      "thesis": "posição residual ilíquida",
      "currentValueLocal": 124.8,
      "currentValue": 124.8,
      "modelTargetWeightPct": 0.0,
      "targetValue": 120.0,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "XOVR",
      "name": "XOVR",
      "themeId": "liquidity",
      "themeLabel": "Liquidez",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 20.58,
      "currentPriceUsd": 20.58,
      "targetPrice": 21.4,
      "targetPriceUsd": 21.4,
      "upsidePct": 4.0,
      "bias": "manter como caixa equivalente",
      "thesis": "equivalente defensivo/cash-like",
      "currentValueLocal": 2058.0,
      "currentValue": 2058.0,
      "modelTargetWeightPct": 4.0,
      "targetValue": 2140.0,
      "status": "No modelo",
      "inModel": true,
      "proposalSymbol": "XOVR",
      "priceDate": "2026-06-01",
      "priceError": ""
    }
  ],
  "residuals": [
    {
      "symbol": "ICG",
      "name": "ICG",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.722585,
      "currentPrice": 0.46,
      "currentPriceUsd": 0.33,
      "targetPrice": 0.46,
      "targetPriceUsd": 0.33,
      "upsidePct": 0.0,
      "bias": "manter apenas residual",
      "thesis": "posição residual CAD; baixa liquidez",
      "currentValueLocal": 3.68,
      "currentValue": 2.66,
      "modelTargetWeightPct": 0.0,
      "targetValue": 2.64,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "HYMC",
      "name": "HYMC",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 32.84,
      "currentPriceUsd": 32.84,
      "targetPrice": 29.56,
      "targetPriceUsd": 29.56,
      "upsidePct": -10.0,
      "bias": "zerar ou residual",
      "thesis": "opcionalidade alta, execução fraca",
      "currentValueLocal": 328.4,
      "currentValue": 328.4,
      "modelTargetWeightPct": 0.0,
      "targetValue": 295.59999999999997,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "NTDOY",
      "name": "NTDOY",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 11.25,
      "currentPriceUsd": 11.25,
      "targetPrice": 12.04,
      "targetPriceUsd": 12.04,
      "upsidePct": 7.0,
      "bias": "reduzir",
      "thesis": "qualidade, mas fora das teses anexas",
      "currentValueLocal": 843.75,
      "currentValue": 843.75,
      "modelTargetWeightPct": 0.0,
      "targetValue": 902.9999999999999,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    },
    {
      "symbol": "USGDF",
      "name": "USGDF",
      "themeId": "residual",
      "themeLabel": "Residual",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.12,
      "currentPriceUsd": 0.12,
      "targetPrice": 0.12,
      "targetPriceUsd": 0.12,
      "upsidePct": 0.0,
      "bias": "zerar se possível",
      "thesis": "posição residual ilíquida",
      "currentValueLocal": 124.8,
      "currentValue": 124.8,
      "modelTargetWeightPct": 0.0,
      "targetValue": 120.0,
      "status": "Residual",
      "inModel": false,
      "proposalSymbol": "",
      "priceDate": "2026-06-01",
      "priceError": ""
    }
  ],
  "watchlist": [
    {
      "name": "American Rare Earths",
      "symbol": "ARR",
      "yahoo": "ARR.AX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.71643,
      "currentPrice": 0.39,
      "currentPriceUsd": 0.28,
      "targetPrice": 0.57,
      "targetPriceUsd": 0.41,
      "upsidePct": 45.0,
      "priority": "alta",
      "thesis": "top 5; terras raras EUA, geopolítica, muito risco",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "AST SpaceMobile",
      "symbol": "ASTS",
      "yahoo": "ASTS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "Espaço",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 105.65,
      "currentPriceUsd": 105.65,
      "targetPrice": 147.91,
      "targetPriceUsd": 147.91,
      "upsidePct": 40.0,
      "priority": "alta",
      "thesis": "top 5; infraestrutura celular via satélite",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "NexGen Energy",
      "symbol": "NXE",
      "yahoo": "NXE",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 11.4,
      "currentPriceUsd": 11.4,
      "targetPrice": 14.82,
      "targetPriceUsd": 14.82,
      "upsidePct": 30.0,
      "priority": "alta",
      "thesis": "top 5; ativo tier-1 em urânio",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Rocket Lab",
      "symbol": "RKLB",
      "yahoo": "RKLB",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Espaço/defesa",
      "category": "Espaço/defesa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 122.39,
      "currentPriceUsd": 122.39,
      "targetPrice": 165.23,
      "targetPriceUsd": 165.23,
      "upsidePct": 35.0,
      "priority": "alta",
      "thesis": "top 5; execução operacional",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "NuScale Power",
      "symbol": "SMR",
      "yahoo": "SMR",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Nuclear SMR",
      "category": "Nuclear SMR",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 12.89,
      "currentPriceUsd": 12.89,
      "targetPrice": 16.76,
      "targetPriceUsd": 16.76,
      "upsidePct": 30.0,
      "priority": "alta",
      "thesis": "top 5; opcionalidade em SMRs",
      "source": "Análise top 5 / Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "MP Materials",
      "symbol": "MP",
      "yahoo": "MP",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 69.29,
      "currentPriceUsd": 69.29,
      "targetPrice": 83.15,
      "targetPriceUsd": 83.15,
      "upsidePct": 20.0,
      "priority": "media",
      "thesis": "produção de rare earths nos EUA; menor risco que ARR",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Lynas Rare Earths",
      "symbol": "LYC",
      "yahoo": "LYC.AX",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.71643,
      "currentPrice": 18.67,
      "currentPriceUsd": 13.38,
      "targetPrice": 21.47,
      "targetPriceUsd": 15.38,
      "upsidePct": 15.0,
      "priority": "media",
      "thesis": "cadeia ex-China em escala",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Ucore Rare Metals",
      "symbol": "Ucore",
      "yahoo": "UURAF",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 4.09,
      "currentPriceUsd": 4.09,
      "targetPrice": 5.52,
      "targetPriceUsd": 5.52,
      "upsidePct": 35.0,
      "priority": "media",
      "thesis": "refino/separação, similar a ARR",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Aclara Resources",
      "symbol": "Aclara",
      "yahoo": "ARA.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "rare_earths",
      "category": "Rare earths",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.722585,
      "currentPrice": 4.45,
      "currentPriceUsd": 3.22,
      "targetPrice": 5.78,
      "targetPriceUsd": 4.18,
      "upsidePct": 30.0,
      "priority": "media",
      "thesis": "heavy rare earths com narrativa ESG",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Energy Fuels",
      "symbol": "UUUU",
      "yahoo": "UUUU",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Urânio/rare earths",
      "category": "Urânio/rare earths",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 17.62,
      "currentPriceUsd": 17.62,
      "targetPrice": 22.03,
      "targetPriceUsd": 22.03,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "urânio + monazita + rare earths",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Denison Mines",
      "symbol": "DNN",
      "yahoo": "DNN",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 3.43,
      "currentPriceUsd": 3.43,
      "targetPrice": 4.29,
      "targetPriceUsd": 4.29,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "ISR optionality no ciclo nuclear",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Global Atomic",
      "symbol": "GLO",
      "yahoo": "GLO.TO",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.722585,
      "currentPrice": 0.74,
      "currentPriceUsd": 0.53,
      "targetPrice": 0.96,
      "targetPriceUsd": 0.7,
      "upsidePct": 30.0,
      "priority": "baixa",
      "thesis": "alto leverage com risco Níger",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Deep Yellow",
      "symbol": "DYL",
      "yahoo": "DYL.AX",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "Australia",
      "currency": "AUD",
      "currencyRaw": "AUD",
      "fxToUsd": 0.71643,
      "currentPrice": 1.6,
      "currentPriceUsd": 1.14,
      "targetPrice": 1.91,
      "targetPriceUsd": 1.37,
      "upsidePct": 20.0,
      "priority": "media",
      "thesis": "ciclo nuclear longo",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Fission Uranium",
      "symbol": "FCU",
      "yahoo": "FCU.TO",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "uranium",
      "category": "Urânio",
      "region": "Canada",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 20.0,
      "priority": "media",
      "thesis": "Athabasca estratégico",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Ivanhoe Mines",
      "symbol": "IVN",
      "yahoo": "IVN.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.722585,
      "currentPrice": 12.76,
      "currentPriceUsd": 9.22,
      "targetPrice": 15.06,
      "targetPriceUsd": 10.88,
      "upsidePct": 18.0,
      "priority": "media",
      "thesis": "opcionalidade global em cobre",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Solaris Resources",
      "symbol": "SLS",
      "yahoo": "SLS.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.722585,
      "currentPrice": 14.75,
      "currentPriceUsd": 10.66,
      "targetPrice": 18.44,
      "targetPriceUsd": 13.32,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "exploração de cobre; alto risco",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Arizona Sonoran Copper",
      "symbol": "ASCU",
      "yahoo": "ASCU.TO",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "CAD",
      "currencyRaw": "CAD",
      "fxToUsd": 0.722585,
      "currentPrice": 10.26,
      "currentPriceUsd": 7.41,
      "targetPrice": 12.31,
      "targetPriceUsd": 8.9,
      "upsidePct": 20.0,
      "priority": "baixa",
      "thesis": "cobre doméstico americano",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "NGEx Minerals",
      "symbol": "NGEX",
      "yahoo": "NGEX.V",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Cobre",
      "region": "Canada",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 30.0,
      "priority": "baixa",
      "thesis": "altíssimo risco/recompensa",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Sigma Lithium",
      "symbol": "SGML",
      "yahoo": "SGML",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "Brazil",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 16.36,
      "currentPriceUsd": 16.36,
      "targetPrice": 20.45,
      "targetPriceUsd": 20.45,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "Brasil + ESG + spodumene",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Patriot Battery Metals",
      "symbol": "PMET",
      "yahoo": "PMET.V",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "Canada",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "opcionalidade canadense",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Atlantic Lithium",
      "symbol": "ALL",
      "yahoo": "ALL.L",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "United Kingdom",
      "currency": "GBP",
      "currencyRaw": "GBp",
      "fxToUsd": 1.346,
      "currentPrice": 0.17,
      "currentPriceUsd": 0.22,
      "targetPrice": 0.2,
      "targetPriceUsd": 0.27,
      "upsidePct": 20.0,
      "priority": "baixa",
      "thesis": "Gana + opcionalidade africana",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Lithium Argentina",
      "symbol": "LAAC",
      "yahoo": "LAAC",
      "themeId": "minerals",
      "themeLabel": "Minerais criticos",
      "studyBucket": "copper_lithium",
      "category": "Lítio",
      "region": "Argentina",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 0.0,
      "currentPriceUsd": 0.0,
      "targetPrice": 0.0,
      "targetPriceUsd": 0.0,
      "upsidePct": 18.0,
      "priority": "baixa",
      "thesis": "ex-Lithium Americas Argentina",
      "source": "Stock Watch",
      "priceError": "HTTP Error 404: Not Found",
      "priceDate": ""
    },
    {
      "name": "Kratos",
      "symbol": "KTOS",
      "yahoo": "KTOS",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "Defesa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 63.49,
      "currentPriceUsd": 63.49,
      "targetPrice": 74.92,
      "targetPriceUsd": 74.92,
      "upsidePct": 18.0,
      "priority": "media",
      "thesis": "drones e sistemas autônomos",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Palantir",
      "symbol": "PLTR",
      "yahoo": "PLTR",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "IA/defesa",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 160.65,
      "currentPriceUsd": 160.65,
      "targetPrice": 179.93,
      "targetPriceUsd": 179.93,
      "upsidePct": 12.0,
      "priority": "media",
      "thesis": "IA militar/inteligência; valuation alto",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Red Cat",
      "symbol": "RCAT",
      "yahoo": "RCAT",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Defesa drones",
      "category": "Defesa drones",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 14.84,
      "currentPriceUsd": 14.84,
      "targetPrice": 20.03,
      "targetPriceUsd": 20.03,
      "upsidePct": 35.0,
      "priority": "baixa",
      "thesis": "microcap em drones militares",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "BlackSky",
      "symbol": "BKSY",
      "yahoo": "BKSY",
      "themeId": "defense_space",
      "themeLabel": "Defesa e espaco",
      "studyBucket": "defense_space",
      "category": "Espaço",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 42.38,
      "currentPriceUsd": 42.38,
      "targetPrice": 52.98,
      "targetPriceUsd": 52.98,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "imagens em tempo real",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Planet Labs",
      "symbol": "PL",
      "yahoo": "PL",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "Espaço/dados",
      "category": "Espaço/dados",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 46.46,
      "currentPriceUsd": 46.46,
      "targetPrice": 56.68,
      "targetPriceUsd": 56.68,
      "upsidePct": 22.0,
      "priority": "baixa",
      "thesis": "dados orbitais + IA",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Recursion",
      "symbol": "RXRX",
      "yahoo": "RXRX",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "ai_biotech",
      "category": "AI biotech",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 3.79,
      "currentPriceUsd": 3.79,
      "targetPrice": 4.74,
      "targetPriceUsd": 4.74,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "drug discovery + IA",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Beam Therapeutics",
      "symbol": "BEAM",
      "yahoo": "BEAM",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "ai_biotech",
      "category": "Biotech",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 31.14,
      "currentPriceUsd": 31.14,
      "targetPrice": 38.92,
      "targetPriceUsd": 38.92,
      "upsidePct": 25.0,
      "priority": "baixa",
      "thesis": "base editing",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "CRISPR Therapeutics",
      "symbol": "CRSP",
      "yahoo": "CRSP",
      "themeId": "tail",
      "themeLabel": "Cauda especulativa",
      "studyBucket": "ai_biotech",
      "category": "Biotech",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 54.19,
      "currentPriceUsd": 54.19,
      "targetPrice": 65.03,
      "targetPriceUsd": 65.03,
      "upsidePct": 20.0,
      "priority": "baixa",
      "thesis": "gene editing com opcionalidade",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Oklo",
      "symbol": "OKLO",
      "yahoo": "OKLO",
      "themeId": "uranium",
      "themeLabel": "Uranio e nuclear",
      "studyBucket": "nuclear",
      "category": "Nuclear",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 66.89,
      "currentPriceUsd": 66.89,
      "targetPrice": 83.61,
      "targetPriceUsd": 83.61,
      "upsidePct": 25.0,
      "priority": "media",
      "thesis": "microreatores + IA/energia",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Cadiz",
      "symbol": "CDZI",
      "yahoo": "CDZI",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "studyBucket": "water",
      "category": "Água",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 4.7,
      "currentPriceUsd": 4.7,
      "targetPrice": 5.4,
      "targetPriceUsd": 5.4,
      "upsidePct": 15.0,
      "priority": "baixa",
      "thesis": "escassez hídrica",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Nutrien",
      "symbol": "NTR",
      "yahoo": "NTR",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "studyBucket": "agriculture",
      "category": "Agricultura",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 69.57,
      "currentPriceUsd": 69.57,
      "targetPrice": 75.14,
      "targetPriceUsd": 75.14,
      "upsidePct": 8.0,
      "priority": "media",
      "thesis": "potássio/fertilizantes estratégicos",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    },
    {
      "name": "Mosaic",
      "symbol": "MOS",
      "yahoo": "MOS",
      "themeId": "quality",
      "themeLabel": "Nucleo qualidade",
      "studyBucket": "agriculture",
      "category": "Agricultura",
      "region": "United States",
      "currency": "USD",
      "currencyRaw": "USD",
      "fxToUsd": 1.0,
      "currentPrice": 23.33,
      "currentPriceUsd": 23.33,
      "targetPrice": 25.2,
      "targetPriceUsd": 25.2,
      "upsidePct": 8.0,
      "priority": "media",
      "thesis": "segurança alimentar global",
      "source": "Stock Watch",
      "priceError": "",
      "priceDate": "2026-06-01"
    }
  ],
  "exports": {
    "marketPricesFile": "exports/market-prices.csv",
    "fxRatesFile": "exports/fx-rates.csv",
    "scenarioSummaryFile": "exports/scenario-summary.csv",
    "scenarioFiles": [
      {
        "id": "study",
        "label": "Base do estudo",
        "file": "scenario-study.csv"
      },
      {
        "id": "defensive",
        "label": "Defensivo global",
        "file": "scenario-defensive.csv"
      },
      {
        "id": "convex",
        "label": "Convexidade",
        "file": "scenario-convex.csv"
      }
    ],
    "publicDataFile": "public/data.js"
  }
};
